#!/bin/bash

# Проверка наличия сообщения коммита
if [ -z "$1" ]; then
  echo "Ошибка: Укажите сообщение для коммита!"
  exit 1
fi

# Локальные команды
git add .
git commit --allow-empty -m "$1"
git push

# Удаленные команды
ssh arenatickets "nvm use 18 && cd /var/www/arenatickets_admin && git pull && yarn && yarn build"

